#pragma config(Motor,  port2,           frontl,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           frontr,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backl,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           backr,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * @file    main.c
 * @brief   This file contains the base for competiton code.
 * @details The three sections include Pre-Auton, Auton, and User
 *          Control.
 *
 * @author		Sean Kelley      sgtkode01@gmail.com
 * @author		Bernard Suwirjo  bsuwirjo@gmail.com
 * @author 		Spencer Couture  spence.couture@gmail.com
 */


#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// all functions for competition code
#include "functions.c"


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Move Forward
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Moves the bot forward. Enables motors {frontl, frontr, backl, backr} for __ seconds
 */
void forward(int seconds){
motor[frontl] = 100;
motor[backl] = 100;
motor[frontr] = 100;
motor[backr] = 100;
wait1Msec(seconds*1000);
motor[frontl] = 0;
motor[backl] = 0;
motor[frontr] = 0;
motor[backr] = 0;
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Move Backward
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Moves the bot backward. Enables motors {frontl, frontr, backl, backr} for __ seconds
 */
void backward(int seconds){
motor[frontl] = -100;
motor[backl] = -100;
motor[frontr] = -100;
motor[backr] = -100;
wait1Msec(seconds*1000);
motor[frontl] = 0;
motor[backl] = 0;
motor[frontr] = 0;
motor[backr] = 0;
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Rotate Right
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Rotates the bot to the right. Enables motors {frontl, frontr, backl, backr} for __ seconds
 */
void rotateRight(int seconds){
motor[frontr] = -100;
motor[backr] = -100;
motor[frontl] = 100;
motor[backl] = 100;
wait1Msec(seconds*1000);
}


/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Rotate Left
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Rotates the bot to the left. Enables motors {frontl, frontr, backl, backr} for __ seconds
 */
void rotateLeft(int seconds){
motor[frontr] = 100;
motor[backr] = 100;
motor[frontl] = -100;
motor[backl] = -100;
wait1Msec(seconds*1000);
}







/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Pre-Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period before autonomous when bot cannot move, but minimal code can run
 */
void pre_auton()
{
 bStopTasksBetweenModes = true;
}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period of match when bot is using only code to operate.
 */
task autonomous(){

}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
/////////////////////////////////////////////////////////////////////////////////////////

/**
 * Period of match when driver controls the bot
 */
task usercontrol(){


  while (true)
	{
    if(bVEXNETActive){


      /////////////////////////////////////////////////////////////////////////////////////////
      //
      //                                      Drive
      //
      /////////////////////////////////////////////////////////////////////////////////////////
  		motor[BR] = vexRT[Ch2];
  		motor[FR] = vexRT[Ch2];
  		motor[BL] = vexRT[Ch3];
  		motor[FL] = vexRT[Ch3];

      wait1Msec(10);
    }
	}
}
